// <auto-generated />
using System;
using DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250809160217_last versio")]
    partial class lastversio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Data.Models.AdviceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdvisorAvailabilityId")
                        .HasColumnType("int");

                    b.Property<int?>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ConfirmedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Response")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Review")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorAvailabilityId");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("UserId");

                    b.ToTable("AdviceRequests");
                });

            modelBuilder.Entity("DAL.Data.Models.AdvisorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdviceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<TimeSpan>("Time")
                        .HasColumnType("time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdviceRequestId")
                        .IsUnique()
                        .HasFilter("[AdviceRequestId] IS NOT NULL");

                    b.HasIndex("AdvisorId");

                    b.ToTable("AdvisorAvailabilities");
                });

            modelBuilder.Entity("DAL.Data.Models.Complaint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Resolution")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("DAL.Data.Models.Consultation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConsultationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Consultations");
                });

            modelBuilder.Entity("DAL.Data.Models.HelpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HelpTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HelpTypeId");

                    b.ToTable("HelpRequests");
                });

            modelBuilder.Entity("DAL.Data.Models.HelpType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HelpTypes");
                });

            modelBuilder.Entity("DAL.Data.Models.HomePage.HeroSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MainTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stats1Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stats1Value")
                        .HasColumnType("int");

                    b.Property<string>("Stats2Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stats2Value")
                        .HasColumnType("int");

                    b.Property<string>("Stats3Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stats3Value")
                        .HasColumnType("int");

                    b.Property<string>("Stats4Label")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stats4Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HeroSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundImageUrl = "/images/hero-bg.jpg",
                            MainTitle = "مرحباً بكم في موقعنا",
                            Stats1Label = "عدد المستفيدين",
                            Stats1Value = 1500,
                            Stats2Label = "المشاريع المكتملة",
                            Stats2Value = 120,
                            Stats3Label = "المتطوعين",
                            Stats3Value = 300,
                            Stats4Label = "سنوات الخبرة",
                            Stats4Value = 10
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.HomePage.HomeVideoSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeVideoSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "فيديو قصير يوضح أهم الأنشطة والخدمات التي نقدمها.",
                            Title = "تعرف على خدماتنا",
                            VideoUrl = "https://www.youtube.com/watch?v=abcd1234"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.HomePage.TrendSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ButtonUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrendSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonText = "المزيد",
                            ButtonUrl = "/initiatives",
                            Description = "تعرف على آخر المبادرات والبرامج التي أطلقناها لخدمة المجتمع.",
                            ImageUrl = "/images/trend.jpg",
                            Title = "أحدث مبادراتنا"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<int>("ConsultationType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ZoomRoomUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Advisors");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.DynamicPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("DynamicPages");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.DynamicPageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DynamicPageId")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("DynamicPageId");

                    b.ToTable("DynamicPageItems");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Mediation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mediations");
                });

            modelBuilder.Entity("DAL.Data.Models.ImagesLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImagesLibrary");
                });

            modelBuilder.Entity("DAL.Data.Models.Lecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ConsultationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ConsultationId");

                    b.ToTable("Lectures");
                });

            modelBuilder.Entity("DAL.Data.Models.NavItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("href")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NavigationItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            href = "/home",
                            label = "الرئيسية"
                        },
                        new
                        {
                            Id = 2,
                            href = "/about-layout/about",
                            label = "عن الجمعية"
                        },
                        new
                        {
                            Id = 3,
                            href = "/governance/regulations",
                            label = "الحوكمة"
                        },
                        new
                        {
                            Id = 4,
                            href = "/help-layout/we-offer",
                            label = "طلبات المساعدة"
                        },
                        new
                        {
                            Id = 5,
                            href = "/support-layout/bank-accounts",
                            label = "المشاركة في الدعم"
                        },
                        new
                        {
                            Id = 6,
                            href = "/blank-page",
                            label = "التنمية وإصلاح ذات البين"
                        },
                        new
                        {
                            Id = 7,
                            href = "/investment-layout/real-state",
                            label = "النشاط الاستثماري"
                        },
                        new
                        {
                            Id = 8,
                            href = "/medcineLayout/GeneralDefinition",
                            label = "الخدمات الطبية"
                        },
                        new
                        {
                            Id = 9,
                            href = "/volunteer-layout/unit",
                            label = "التطوع"
                        },
                        new
                        {
                            Id = 10,
                            href = "/about-layout/contact-phone",
                            label = "التواصل والشكاوى"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.NewsImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewsItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NewsItemId");

                    b.ToTable("NewsImages");
                });

            modelBuilder.Entity("DAL.Data.Models.NewsItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("NewsItems");
                });

            modelBuilder.Entity("DAL.Data.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DAL.Data.Models.Pages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NavItemsId")
                        .HasColumnType("int");

                    b.Property<string>("subLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subTilte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NavItemsId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            NavItemsId = 2,
                            subLink = "/about-layout/vision-mission",
                            subTilte = " الرسالة والرؤية"
                        },
                        new
                        {
                            Id = 1002,
                            NavItemsId = 2,
                            subLink = "/about-layout/about-summary",
                            subTilte = "نبذة عن الجمعية"
                        },
                        new
                        {
                            Id = 1003,
                            NavItemsId = 2,
                            subLink = "/about-layout/tasks-authorities",
                            subTilte = "مهام الجمعية"
                        },
                        new
                        {
                            Id = 1004,
                            NavItemsId = 2,
                            subLink = "/about-layout/general-assembly",
                            subTilte = "الجمعية العمومية"
                        },
                        new
                        {
                            Id = 1005,
                            NavItemsId = 2,
                            subLink = "/about-layout/board-members",
                            subTilte = "مجلس الأدارة"
                        },
                        new
                        {
                            Id = 1006,
                            NavItemsId = 2,
                            subLink = "/about-layout/organizational-structure",
                            subTilte = "الهيكل النظيمى"
                        },
                        new
                        {
                            Id = 1007,
                            NavItemsId = 2,
                            subLink = "/about-layout/service-locations",
                            subTilte = "مواقع العمل"
                        },
                        new
                        {
                            Id = 1008,
                            NavItemsId = 2,
                            subLink = "/about-layout/ImageLibrary",
                            subTilte = "مكتبة الصور والفيديوهات"
                        },
                        new
                        {
                            Id = 1101,
                            NavItemsId = 3,
                            subLink = "/governance/regulations",
                            subTilte = "الأنظمة واللوائح "
                        },
                        new
                        {
                            Id = 1102,
                            NavItemsId = 3,
                            subLink = "/governance/policies",
                            subTilte = "السياسات"
                        },
                        new
                        {
                            Id = 1103,
                            NavItemsId = 3,
                            subLink = "/blank-page",
                            subTilte = "التقارير السنوية"
                        },
                        new
                        {
                            Id = 1104,
                            NavItemsId = 3,
                            subLink = "/governance/quarterly-reports",
                            subTilte = "التقارير الربعية"
                        },
                        new
                        {
                            Id = 1105,
                            NavItemsId = 3,
                            subLink = "/governance/financial-reports",
                            subTilte = "القوائم المالية"
                        },
                        new
                        {
                            Id = 1106,
                            NavItemsId = 3,
                            subLink = "/blank-page",
                            subTilte = "معايير الحوكمة"
                        },
                        new
                        {
                            Id = 1107,
                            NavItemsId = 3,
                            subLink = "/governance/governance-evaluation",
                            subTilte = "نتائج تقييم الحوكمة"
                        },
                        new
                        {
                            Id = 1108,
                            NavItemsId = 3,
                            subLink = "/governance/strategic-plans",
                            subTilte = "الخطة الاستراتيجية"
                        },
                        new
                        {
                            Id = 1109,
                            NavItemsId = 3,
                            subLink = "/governance/operational-plan",
                            subTilte = "الخطة التشغيلية"
                        },
                        new
                        {
                            Id = 1110,
                            NavItemsId = 3,
                            subLink = "/governance/Goals",
                            subTilte = "الأهداف"
                        },
                        new
                        {
                            Id = 1201,
                            NavItemsId = 4,
                            subLink = "/help-layout/we-offer",
                            subTilte = "ماذا نقدم؟"
                        },
                        new
                        {
                            Id = 1202,
                            NavItemsId = 4,
                            subLink = "/help-layout/eligible",
                            subTilte = "الفئات المستحقة"
                        },
                        new
                        {
                            Id = 1203,
                            NavItemsId = 4,
                            subLink = "/help-layout/requirements",
                            subTilte = "المستندات المطلوبة"
                        },
                        new
                        {
                            Id = 1204,
                            NavItemsId = 4,
                            subLink = "/HelpPeopole",
                            subTilte = "الحصول على الخدمة"
                        },
                        new
                        {
                            Id = 1205,
                            NavItemsId = 4,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات"
                        },
                        new
                        {
                            Id = 1301,
                            NavItemsId = 5,
                            subLink = "/blank-page",
                            subTilte = "نشاطات الجمعية"
                        },
                        new
                        {
                            Id = 1302,
                            NavItemsId = 5,
                            subLink = "/support-layout/bank-accounts",
                            subTilte = "حسابات الجمعية"
                        },
                        new
                        {
                            Id = 1303,
                            NavItemsId = 5,
                            subLink = "https://jkmm.org.sa/ElectronicServices/Donate#",
                            subTilte = "الحصول على الخدمة"
                        },
                        new
                        {
                            Id = 1304,
                            NavItemsId = 5,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات"
                        },
                        new
                        {
                            Id = 1401,
                            NavItemsId = 6,
                            subLink = "/blank-page",
                            subTilte = "تعريف عام بالنشاط"
                        },
                        new
                        {
                            Id = 1402,
                            NavItemsId = 6,
                            subLink = "/all-consultants",
                            subTilte = "طلب استشارة أون لاين"
                        },
                        new
                        {
                            Id = 1403,
                            NavItemsId = 6,
                            subLink = "/RequesrRepair",
                            subTilte = "طلب إصلاح ذات البين"
                        },
                        new
                        {
                            Id = 1404,
                            NavItemsId = 6,
                            subLink = "/complaints",
                            subTilte = "تقديم شكوى"
                        },
                        new
                        {
                            Id = 1405,
                            NavItemsId = 6,
                            subLink = "/awarness-lecture",
                            subTilte = "محاضرات توعوية"
                        },
                        new
                        {
                            Id = 1406,
                            NavItemsId = 6,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات"
                        },
                        new
                        {
                            Id = 1501,
                            NavItemsId = 7,
                            subLink = "/blank-page",
                            subTilte = "تعريف عام بالنشاط"
                        },
                        new
                        {
                            Id = 1502,
                            NavItemsId = 7,
                            subLink = "/investment-layout/real-state",
                            subTilte = "الاستثمارات العقارية"
                        },
                        new
                        {
                            Id = 1503,
                            NavItemsId = 7,
                            subLink = "/investment-layout/invest-project",
                            subTilte = "المشروعات الاستثمارية"
                        },
                        new
                        {
                            Id = 1504,
                            NavItemsId = 7,
                            subLink = "/blank-page",
                            subTilte = "مشروعات التنمية المستدامة"
                        },
                        new
                        {
                            Id = 1505,
                            NavItemsId = 7,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات"
                        },
                        new
                        {
                            Id = 1601,
                            NavItemsId = 8,
                            subLink = "/medcineLayout/GeneralDefinition",
                            subTilte = "تعريف عام بالنشاط"
                        },
                        new
                        {
                            Id = 1602,
                            NavItemsId = 8,
                            subLink = "/medcineLayout/MedicalCenter",
                            subTilte = "مركز غسيل الكلى"
                        },
                        new
                        {
                            Id = 1603,
                            NavItemsId = 8,
                            subLink = "/medcineLayout/HairingCenter",
                            subTilte = "مركز السمع والنطق"
                        },
                        new
                        {
                            Id = 1604,
                            NavItemsId = 8,
                            subLink = "/blank-page",
                            subTilte = "الخدمات الطبية من خارج الجمعية"
                        },
                        new
                        {
                            Id = 1605,
                            NavItemsId = 8,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات"
                        },
                        new
                        {
                            Id = 1701,
                            NavItemsId = 9,
                            subLink = "/volunteer-layout/unit",
                            subTilte = "تعريف بالنشاط"
                        },
                        new
                        {
                            Id = 1702,
                            NavItemsId = 9,
                            subLink = "/blank-page",
                            subTilte = "ميثاق التطوع"
                        },
                        new
                        {
                            Id = 1703,
                            NavItemsId = 9,
                            subLink = "/volunteer-layout/volunteer-medical",
                            subTilte = "مجالات التطوع"
                        },
                        new
                        {
                            Id = 1704,
                            NavItemsId = 9,
                            subLink = "/Voulenteer",
                            subTilte = "الحصول على الخدمة"
                        },
                        new
                        {
                            Id = 1705,
                            NavItemsId = 9,
                            subLink = "/blank-page",
                            subTilte = "إحصاءات التطوع"
                        },
                        new
                        {
                            Id = 1801,
                            NavItemsId = 10,
                            subLink = "/blank-page",
                            subTilte = "تقديم مقترح"
                        },
                        new
                        {
                            Id = 1802,
                            NavItemsId = 10,
                            subLink = "/complaints",
                            subTilte = "تقديم شكوى"
                        },
                        new
                        {
                            Id = 1803,
                            NavItemsId = 10,
                            subLink = "/Satisfaction",
                            subTilte = "قياسات الرضا"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.ReconcileRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RequestText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ReconcileRequests");
                });

            modelBuilder.Entity("DAL.Data.Models.ServiceOffering", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ServiceOfferings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Default Description",
                            Title = "Default Title"
                        });
                });

            modelBuilder.Entity("DAL.Data.Models.ServiceOfferingItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ServiceOfferingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOfferingId");

                    b.ToTable("ServiceOfferingItems");
                });

            modelBuilder.Entity("DAL.Data.Models.VideosLibrary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideosLibraries");
                });

            modelBuilder.Entity("DAL.Data.Models.VolunteerApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("VolunteerApplications");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DAL.Data.Models.AdviceRequest", b =>
                {
                    b.HasOne("DAL.Data.Models.AdvisorAvailability", null)
                        .WithMany()
                        .HasForeignKey("AdvisorAvailabilityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Data.Models.IdentityModels.Advisor", "Advisor")
                        .WithMany("AdviceRequests")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.Data.Models.Consultation", "Consultation")
                        .WithMany("AdviceRequests")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithMany("AdviceRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Consultation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.AdvisorAvailability", b =>
                {
                    b.HasOne("DAL.Data.Models.AdviceRequest", "AdviceRequest")
                        .WithOne()
                        .HasForeignKey("DAL.Data.Models.AdvisorAvailability", "AdviceRequestId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Data.Models.IdentityModels.Advisor", "Advisor")
                        .WithMany("Availabilities")
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AdviceRequest");

                    b.Navigation("Advisor");
                });

            modelBuilder.Entity("DAL.Data.Models.Complaint", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.HelpRequest", b =>
                {
                    b.HasOne("DAL.Data.Models.HelpType", "HelpType")
                        .WithMany()
                        .HasForeignKey("HelpTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HelpType");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Admin", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithOne("Admin")
                        .HasForeignKey("DAL.Data.Models.IdentityModels.Admin", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Advisor", b =>
                {
                    b.HasOne("DAL.Data.Models.Consultation", "Consultation")
                        .WithMany("Advisors")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithOne("Advisor")
                        .HasForeignKey("DAL.Data.Models.IdentityModels.Advisor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.DynamicPageItem", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.DynamicPage", "DynamicPage")
                        .WithMany("Items")
                        .HasForeignKey("DynamicPageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DynamicPage");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Mediation", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithOne("Mediation")
                        .HasForeignKey("DAL.Data.Models.IdentityModels.Mediation", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.Lecture", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", null)
                        .WithMany("CreatedLectures")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("DAL.Data.Models.Consultation", null)
                        .WithMany("Lectures")
                        .HasForeignKey("ConsultationId");
                });

            modelBuilder.Entity("DAL.Data.Models.NewsImage", b =>
                {
                    b.HasOne("DAL.Data.Models.NewsItem", "NewsItem")
                        .WithMany("Images")
                        .HasForeignKey("NewsItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsItem");
                });

            modelBuilder.Entity("DAL.Data.Models.Pages", b =>
                {
                    b.HasOne("DAL.Data.Models.NavItems", "NavItems")
                        .WithMany("pages")
                        .HasForeignKey("NavItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NavItems");
                });

            modelBuilder.Entity("DAL.Data.Models.ReconcileRequest", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DAL.Data.Models.ServiceOfferingItem", b =>
                {
                    b.HasOne("DAL.Data.Models.ServiceOffering", "ServiceOffering")
                        .WithMany("ServiceItem")
                        .HasForeignKey("ServiceOfferingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceOffering");
                });

            modelBuilder.Entity("DAL.Data.Models.VolunteerApplication", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", "User")
                        .WithMany("VolunteerApplications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("DAL.Data.Models.IdentityModels.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DAL.Data.Models.Consultation", b =>
                {
                    b.Navigation("AdviceRequests");

                    b.Navigation("Advisors");

                    b.Navigation("Lectures");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.Advisor", b =>
                {
                    b.Navigation("AdviceRequests");

                    b.Navigation("Availabilities");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.ApplicationUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("AdviceRequests");

                    b.Navigation("Advisor");

                    b.Navigation("Complaints");

                    b.Navigation("CreatedLectures");

                    b.Navigation("Mediation");

                    b.Navigation("VolunteerApplications");
                });

            modelBuilder.Entity("DAL.Data.Models.IdentityModels.DynamicPage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("DAL.Data.Models.NavItems", b =>
                {
                    b.Navigation("pages");
                });

            modelBuilder.Entity("DAL.Data.Models.NewsItem", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("DAL.Data.Models.ServiceOffering", b =>
                {
                    b.Navigation("ServiceItem");
                });
#pragma warning restore 612, 618
        }
    }
}
